# Generated by Django 3.2.11 on 2022-02-20 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0009_htesthubvisitedrecently'),
    ]

    operations = [
        migrations.CreateModel(
            name='HTestCaseModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.IntegerField(default=0, verbose_name='父节点的id')),
                ('name', models.CharField(default='', max_length=100, verbose_name='名称')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('h_test_hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_api.htesthub')),
            ],
        ),
    ]
