# Generated by Django 3.2.11 on 2022-03-06 03:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_api', '0010_htestcasemodule'),
    ]

    operations = [
        migrations.CreateModel(
            name='HTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=300, verbose_name='描述')),
                ('pre_step', models.TextField(default='', verbose_name='前置条件')),
                ('step', models.TextField(default='', verbose_name='描述')),
                ('post_step', models.TextField(default='', verbose_name='后置条件')),
                ('expect', models.TextField(default='', verbose_name='预期结果')),
                ('status_id', models.IntegerField(default=0, verbose_name='状态')),
                ('priority_id', models.IntegerField(default=0, verbose_name='优先级')),
                ('type_id', models.IntegerField(default=0, verbose_name='类型')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('h_test_hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_api.htesthub')),
                ('h_test_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_api.htestcasemodule')),
            ],
        ),
    ]
