# Generated by Django 3.2.11 on 2022-04-23 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0012_htestplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='htestplan',
            name='block_num',
            field=models.IntegerField(default=0, verbose_name='阻塞个数'),
        ),
        migrations.AddField(
            model_name='htestplan',
            name='failed_num',
            field=models.IntegerField(default=0, verbose_name='失败个数'),
        ),
        migrations.AddField(
            model_name='htestplan',
            name='skip_num',
            field=models.IntegerField(default=0, verbose_name='跳过个数'),
        ),
        migrations.AddField(
            model_name='htestplan',
            name='success_num',
            field=models.IntegerField(default=0, verbose_name='成功个数'),
        ),
        migrations.CreateModel(
            name='HTestPlanRelateTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_status_id', models.IntegerField(default=1, verbose_name='执行状态')),
                ('h_test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_api.htestcase')),
                ('h_test_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_api.htestplan')),
            ],
        ),
    ]
